### PR TITLE
Force CCC version for NEI

### PR DESCRIPTION
**Pull request by kenzierocks**
Fixes error with NEI looking for 1.0.4 but getting 1.0.2. Doesn't break anything else.

### CODE REVIEW

**Comment by MrTJP** [comment]
Hmm, what is the problem exactly?

**Comment by kenzierocks** [comment]
I couldn't launch without 1.0.4, but the dependency resolution gave 1.0.2 instead. I forced it to 1.0.4.

**Comment by MrTJP** [comment]
Since CCC is a coremod, don't you need to download/install into the mods directory anyway? Thats what I do, and then I unlike the one auto downloaded by gradle...

**Comment by kenzierocks** [comment]
Apparently not with GradleStart.

**Comment by MrTJP** [comment]
Instead of this, im going to bump NEI dep version to 1.0.4.95, which depends on CCC 1.0.5.

**Comment by kenzierocks** [comment]
Works for me!

**Pull request closed without merging**
