### PR TITLE
Inverting colors to fix CLC compat

### PR DESCRIPTION
**Pull request by CptSpaceToaster**
This should be too crazy...

### CODE REVIEW

**Comment by MrTJP** [comment]
Actually, problem was that I was using 0 to 255 scaled color values for rgb, but your API was expecting a 0 to 15 scale.  Fixed with ab4ef6fa112f7c2c93cf3b3ace437b72ba3d0b7f

And good, you fixed your API's dependency on your mod classes :P

**Comment by CptSpaceToaster** [comment]
:+1:

**Comment by MrTJP** [comment]
Hmm. Why deprecate ability to provide own brightness?

**Comment by CptSpaceToaster** [comment]
I intend to leave it in... but I wanted to "encourage" users to set the brightness to the maximum color component from the three color channels.  They are related... not independent.

There are issues if you set brightness independently of the colors.  You could make a white light have brightness R = 15, G = 15, B = 15 and L = 3, and it would look like a maximum brightness white block, but remove CLC, and you'll have a L = 3 block.  

This plays into monster spawning, and a number of small "quality of life" changes that I'm not too keen on leaving in.

Other than that... personal preference.  I just marked it deprecated because it's not how I view you should do it.  Feel free to use it anyways.

Also, maven: http://coloredlightscore.us.to/maven/clc/coloredlightscore/ColoredLightsCore/

**Pull request closed without merging**
