### PR TITLE
RomanPlayer22 patch 1 (czech translation add request)

### PR DESCRIPTION
**Pull request by RomanPlayer22**
I made this cause why not (it's a translation)

### CODE REVIEW

**Comment by RomanPlayer22** [comment]
Also  I did fix some typos in the original file (merged a new version of it into the old errored one)

**Review by tomodachi94 — CHANGES_REQUESTED** [review]
This looks good (but I don't speak Czech), except that the file `cs_cz` is in the root of the repository *and* in the translation folder. Can you delete the file `cs_cz.json` in the root?

**Comment by RomanPlayer22** [comment]
@tomodachi94 Thanks for letting me know
I have updated the file in the translation folder
And deleted the one in the root repository

**Review by tomodachi94 — APPROVED** [review]
Lgtm. Thank you for making this!

**Comment by RomanPlayer22** [comment]
Patched once again (Missing translations)

**Comment by RomanPlayer22** [comment]
Waiting for this to be processed....

**Comment by MrTJP** [comment]
Thanks! Merged

**Pull request merged**
