### PR TITLE
Add optional diamond block breaker

### PR DESCRIPTION
**Pull request by Spauldo**
This code adds a diamond block breaker, with the same recipe as that of the regular block breaker except that a diamond pick is used.

The diamond block breaker can break any block that doesn't have a hardness of -1 and isn't bedrock.

It's very expensive (my tunnel bore in my current game would require 750 diamonds to make, a simple 5x5 would take 75), but it's mostly necessary for boring in deep areas where lava and water often meet.  It's great for people like me who used RP2 tunnel bores back in the day - otherwise, low level mining means having to check on the thing every thirty minutes or so.

There's a configuration option to enable or disable the crafting recipe.  It defaults to disabled, so server admins won't be taken by surprise by this.

I'm willing to make any changes deemed necessary to make it fit into the mod better, but as I wrote this for use on my own private household server, it's not going to break my heart if you don't accept the pull request.  I got what I need :)

### CODE REVIEW

**Comment by MrTJP** [comment]
I was going to add this at some point anyway. Will pull when the time comes while I update the mod.

**Comment by Klesh-** [comment]
Translations into Russian and Ukrainian wrong. Correct would be "Разрушитель алмазных блоков" and "Зломщик алмазних блоків"

**Comment by Spauldo** [comment]
Updated Russian and Ukrainian translations.  I don't speak either of those languages so I was relying on Google Translate (figured it'd be better than nothing).

**Comment by bookerthegeek** [comment]
This makes me very happy.

**Pull request merged**
