### PR TITLE
Fix indeterministic compile of ICs

### LINKED ISSUE #1245: [1.10.2] IC Gate state gets screwed up when saving and loading a level
I created an 16 bit programmable binary decoder which acts weird upon placement and world unload/load. For some reason seemingly random wires get activated in the circuit even though there should be no reason for them to be active. The only way I've found to fix it is to enable and disable all inputs, but the problem re-occurs after the world is unloaded and reloaded. From what I can tell the issue is caused by gates that invert their input. The issue occurs with schematics too. Here's an image of the schematic after a world reload. [https://i.imgur.com/ZnWCaiw.png](https://i.imgur.com/ZnWCaiw.png?1)

The gates on the right are NOT gates, the gates on the lower diagonal are XOR gates, and the rest of the gates are AND gates. The bottom and right are inputs while the top is an output

I have tested this with NOT, NAND, and NOR gates

### LINKED ISSUE #1342: [1.12.2] some IC gates get stuck after world reload.
I created this IC for a 16-bit binary to BCD setup using the Double Dabble method.  Sometimes, on a world reload, some of these gates get stuck and will not accept a new state until broken and replaced.  Here is a screenshot of the IC blueprint: 
decoder
This has not happened with any of my other IC gates, except for this one (although it only happened to that gate once, and it has not glitched since): 
clock
Perhaps this is an issue with bundled cables on IC gates?  I am not using bundled cables on any of my other IC gates.

### LINKED ISSUE #1448: IC Chips get scrambled on game load
Any IC I fabricate gets scrambled upon world reload, and requires all of them to be broken and replaced back down to work.  (Note I have only tested in creative where inventory is unlimited and I am placing back down a new IC, haven't tried to see if in survival a broken IC will place back down and work or still be scrambled).  I am on newest version of forge on MC 1.12.2, no other mods installed except for the required prerequisites and Integration, Fabrication, and Lights, compat, and worldedit.

### LINKED ISSUE #1484: Game breaking bug - ICs get scrambled on game load (test case world for #1448 and #1245)
See #1448 and #1245. ProjectRed has had this issue for a while, and 1b4e790fbf14322fbc825db521da34a1a4cf8baf did not fix it.

My hypothesis is that some of the *inputs* get stuck in random states whenever chunks are loaded.

For the same initial configuration, it seems that it's *almost* always the same inputs that get screwed up. It seems the output always ends up being something that is possible for the IC to output, which is why I believe it's the inputs that are getting stuck.

In this test case, I have a 4 to 16 decoder that, most of the time, gets its white input turned on, causing the output to be incremented by 1. In rare cases, the right input (toggle output) gets turned off. In order to fix it, you have to invert whatever input is getting stuck, or you can break and replace the IC. But the problem always comes back when the chunks reload.

[projectred-ic-scrambling-test-case.zip](https://github.com/MrTJP/ProjectRed/files/3239778/projectred-ic-scrambling-test-case.zip)

Screenshot of test case world

Mod versions:

```
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
ForgeMultipart-1.12.2-2.6.0.79-universal.jar
MrTJPCore-1.12.2-2.1.4.38-universal.jar
ProjectRed-1.12.2-4.9.2.110-Base.jar
ProjectRed-1.12.2-4.9.2.110-fabrication.jar
ProjectRed-1.12.2-4.9.2.110-integration.jar
ProjectRed-1.12.2-4.9.2.110-lighting.jar
ProjectRed-1.12.2-4.9.2.110-mechanical.jar
```

This is really frustrating because it makes nearly everything I had planned impossible or impractical.

### PR DESCRIPTION
**Pull request by MrTJP**
Bus signals within ICs get scrambled on world load because although the registers are properly saved, they are not necessarily in the same order when the world is reloaded and the IC is recompiled. So for example, the register representing the white signal could be at index 0 the first time, and then index 15 the next time the IC is compiled.

Fixes #1484, fixes #1448, fixes #1342, fixes #1245

### CODE REVIEW

**Comment by kremlar** [comment]
Clicking the 'redraw' button, selecting a size, and clicking 'start' on blueprint tables(IC Workbench) is causing a crash for me, both with a copy of my current world and on a freshly installed instance. https://pastebin.com/jUXgF44w Existing blueprints I've worked with before display and edit normally, but will still crash when going through redraw.

Aside from the crash, I tested what I already designed and built, and everything that worked before is still working in my project. The first load on the new version still had some junk values, which is probably to be expected, and I haven't seen any scrambling since then.

**Comment by MrTJP** [comment]
Scrambled values are expected at first load, but should be good thereafter. Will investigate the crash.

**Comment by MrTJP** [comment]
Have fixed the client crash on redrawing the blueprint.

**Comment by ccfb3ee765a58cae** [comment]
Just tested 9f6264b0fe611a211c00b62a1b47f457924bcf5e with a couple of ICs with internal bundled cables, nothing funky has popped up yet.

**Pull request merged**
